import "./globals.css"
import { Roboto, Lobster_Two } from "next/font/google"
import Nav from "./components/Nav"
import Hydrate from "./components/Hydrate"
import Footer from "./components/Footer"

//Define main font
const roboto = Roboto({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  variable: "--font-robot",
})
const lobster = Lobster_Two({
  weight: "700",
  subsets: ["latin"],
  variable: "--font-lobster",
})

export const metadata = {
  title: "An app by Gareth",
  description: "Generated by create next app",
  github: "garethwilliams90",
  author: "Gareth Williams",
  // authorUrl: "https://gareth.dev",
  keywords: [
    "nextjs",
    "tailwind",
    "tailwindcss",
    "tailwind-nextjs",
    "tailwindcss-nextjs",
  ],
  // canonical: "https://gareth.dev/",
  image: "https://gareth.dev/images/og.png",
  // ogImage: "https://gareth.dev/images/og.png",
  // ogImageWidth: 1200,
  // ogImageHeight: 630,
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html className={`${roboto.variable} ${lobster.variable}  `} lang="en">
      <Hydrate>
        <Nav />
        {children}
        <Footer />
      </Hydrate>
    </html>
  )
}
